### ISSUE TITLE
Differences between XnatInstaller and OmeroInstaller for creating self-signed SSL certificates

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/ansible-role-ssl-certificates#1]
As mentioned in https://github.com/UCL-MIRSG/ansible-role-postgresql/issues/1#issuecomment-1404007225, there are several differences in the way XnatInstaller and OmeroInstaller handle the creation of self-signed SSL certificates. These differences will need to be accounted for when creating this role.

However, there are also some lower-level differences that I'm unsure how to handle here:

- When generating an OpenSSL CSR, `XnatInstaller` sets the common name to [`xnat_db.host`](https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/blob/0622e3cbcc5ed5132792ca39cd84dc05d8f0ff41/environments/development/group_vars/xnat/vars#L20-L21) for the [server certificate](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/roles/postgresql/tasks/create_pg_server_cert.yml#L22) and [`xnat_web_server.host`](https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/blob/main/environments/development/group_vars/xnat/vars#L10-L11) for the [client certificate](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/roles/create_pg_client_cert/tasks/main.yml#L28). However, `OmeroInstaller` sets both the [server certificate](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/group_vars/db/vars#L32) and [client certificate](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/group_vars/omero/vars#L14) CSR common names to [`omero_db.host`](https://github.com/UCL-MIRSG/OmeroInstallerConfig/blob/581bcdfc0559c0f1b0a1843a7d19ed21af684c33/environments/development/group_vars/dev_omero/vars#L13-L14). Should the same common name be used for both the db and web servers, or should `omero_web.host` be used for the client certificate?

- In `XnatInstaller`, the `db` host has a variable [`postgres.ssl_client_cert_file`](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/group_vars/db.yml#L18) that is the path `/var/lib/pgsql/certs/root.crt`. In `OmeroInstaller`, the `db` host has this same path assigned to a different variable ([`postgres.ssl_ca_file`](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/group_vars/db/vars#L28)). Which variable name is better to use - `postgres.ssl_client_cert_file` or `postgres.ssl_ca_file`?

- After creating the client certificate, `XnatInstaller` [changes the owner, group, and permissions](https://github.com/UCL-MIRSG/XnatInstaller/blob/0fd346ce97186573e89142c7e6aced5bd8ae1341/playbooks/roles/create_pg_client_cert/tasks/main.yml#L42-L47) of the pk8 file. However, `OmeroInstaller` doesn't change these values. Do they need to be changed in this SSL role?

- `XnatInstaller` copies the [server certificate to the client](https://github.com/UCL-MIRSG/XnatInstaller/blob/0fd346ce97186573e89142c7e6aced5bd8ae1341/playbooks/roles/add_pg_server_cert_to_client/tasks/main.yml#L10-L16) and the [client certificate to the server](https://github.com/UCL-MIRSG/XnatInstaller/blob/0fd346ce97186573e89142c7e6aced5bd8ae1341/playbooks/roles/postgresql/tasks/add_pg_client_cert_to_server.yml#L10-L17). `OmeroInstaller` does this too, but it also copies the `ssl_key_file`, `ssl_cert_file`, and `ssl_pk8_file` [from the server to the client](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/roles/omero_server/tasks/main.yml#L48-L70) and the `ssl_key_file` and `ssl_cert_file` [from the client to the server](https://github.com/UCL-MIRSG/OmeroInstaller/blob/509e37ff7714089285fd7950d8f711109dbef1ae/playbooks/roles/postgresql/tasks/add_self_signed_client_cert.yml#L18-L36). Do these extra files need to be copied across?

- `XnatInstaller` sets permissions to `mode: 700` for the certificates directory and `mode: 400` for the key, certificate, and pk8 files. `OmeroInstaller` sets permissions to `mode: 755` for the certificates directory and doesn't explicitly set permissions for the files. Do the permissions need to be set as in `XnatInstaller`?

**Comment by drmatthews** [comment]
> When generating an OpenSSL CSR, XnatInstaller sets the common name to [xnat_db.host](https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/blob/0622e3cbcc5ed5132792ca39cd84dc05d8f0ff41/environments/development/group_vars/xnat/vars#L20-L21) for the [server certificate](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/roles/postgresql/tasks/create_pg_server_cert.yml#L22) and [xnat_web_server.host](https://github.com/UCL-MIRSG/UCLMedicalImagingEnv/blob/main/environments/development/group_vars/xnat/vars#L10-L11) for the [client certificate](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/roles/create_pg_client_cert/tasks/main.yml#L28). However, OmeroInstaller sets both the [server certificate](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/group_vars/db/vars#L32) and [client certificate](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/group_vars/omero/vars#L14) CSR common names to [omero_db.host](https://github.com/UCL-MIRSG/OmeroInstallerConfig/blob/581bcdfc0559c0f1b0a1843a7d19ed21af684c33/environments/development/group_vars/dev_omero/vars#L13-L14). Should the same common name be used for both the db and web servers, or should omero_web.host be used for the client certificate?

This would appear to be a mistake in `OmeroInstaller` - the naming should be as in `XnatInstaller` (although it still works as-is in `OmeroInstaller`).

> In XnatInstaller, the db host has a variable [postgres.ssl_client_cert_file](https://github.com/UCL-MIRSG/XnatInstaller/blob/main/playbooks/group_vars/db.yml#L18) that is the path /var/lib/pgsql/certs/root.crt. In OmeroInstaller, the db host has this same path assigned to a different variable ([postgres.ssl_ca_file](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/group_vars/db/vars#L28)). Which variable name is better to use - postgres.ssl_client_cert_file or postgres.ssl_ca_file?

I appreciate that this looks confusing, but in `OmeroInstaller` I renamed `ssl_client_cert_file` to `ssl_ca_file` because I needed an extra variable for the name of the cert file in the cache directory. In `XnatInstaller` there is a separate cache directory for client and server certs (e.g. `pg_client_cert_cache`). In `OmeroInstaller` I opted for a single cache directory and a variable for the filename in the cache (e.g. `ssl_client_cert_filename`) which was quite similar to a variable already in use. A better approach would be to follow `XnatInstaller` and keep `ssl_client_cert_file` but set a generic variable for the full path in the cache dir (e.g. `ssl_cert_cache_path`).

> XnatInstaller copies the [server certificate to the client](https://github.com/UCL-MIRSG/XnatInstaller/blob/0fd346ce97186573e89142c7e6aced5bd8ae1341/playbooks/roles/add_pg_server_cert_to_client/tasks/main.yml#L10-L16) and the [client certificate to the server](https://github.com/UCL-MIRSG/XnatInstaller/blob/0fd346ce97186573e89142c7e6aced5bd8ae1341/playbooks/roles/postgresql/tasks/add_pg_client_cert_to_server.yml#L10-L17). OmeroInstaller does this too, but it also copies the ssl_key_file, ssl_cert_file, and ssl_pk8_file [from the server to the client](https://github.com/UCL-MIRSG/OmeroInstaller/blob/22ae3cb5413c8795542556065b6719c038fd2316/playbooks/roles/omero_server/tasks/main.yml#L48-L70) and the ssl_key_file and ssl_cert_file [from the client to the server](https://github.com/UCL-MIRSG/OmeroInstaller/blob/509e37ff7714089285fd7950d8f711109dbef1ae/playbooks/roles/postgresql/tasks/add_self_signed_client_cert.yml#L18-L36). Do these extra files need to be copied across?

Probably not. In `OmeroInstaller` copy everything is probably just a left-over from me trying to get a generic role to work. I suggest starting by copying only the cert file.

> XnatInstaller sets permissions to mode: 700 for the certificates directory and mode: 400 for the key, certificate, and pk8 files. OmeroInstaller sets permissions to mode: 755 for the certificates directory and doesn't explicitly set permissions for the files. Do the permissions need to be set as in XnatInstaller?

In `OmeroInstaller` the ownership and permissions of the pk8 file is set during copying. It can be done as in `XnatInstaller` but you'd need a variable for the SSL cert role which sets the owner, group and permission. Which is probably a better approach as it will make it clearer. We would just need to make sure that (in `OmeroInstaller`) `omero_server_system_user` is set before the SSL cert role variables.

**Comment by p-j-smith** [comment]
thanks for clarifying - I think these issues are all addressed by the current version of this role
